### ISSUE TITLE
When new version is available can't login and save products

### ISSUE THREAD

**Issue by taniacr** [E-goi/smart-marketing-for-ps_1.7#25]
Everytime there is a new version available (the modal appears at the top right corner), the customer can't login to the Backoffice in the first try.
And when saving products (new and existent) it gives a generic error message.

After deactivating or upgrading the e-goi module the problem goes away. Already happened in the last 2 or 3 module updates.

PS version: 1.7.8.6

**Comment by renato-gomes** [comment]
We can't reproduce what you are experiencing.
